try:
    result = 45/5
except:
    print("error happend")
finally:
    print("done")